<a href="https://colab.research.google.com/github/Shivam-vachhani/PyTorch-Projects/blob/main/ANN_On_Telecom_Churn_Dataset_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset , DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

In [112]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [113]:
# feature engeineering
df = df.drop(columns=["customerID"])
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors='coerce')
df.dropna(subset=["TotalCharges"],inplace=True)

In [114]:
# Encode yes and no values to 0 and 1 and if three values then 0,1,2 accordingly

Encodable_feilds_two_values=['Partner', 'Dependents', 'PhoneService',  'PaperlessBilling', 'Churn']
Encodable_feilds_three_values= ['MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']
def encoding_values(df):
    for feature in df.columns:
        if feature in Encodable_feilds_two_values:
           df[feature] = df[feature].apply(lambda x:1 if x == "Yes" else 0)
        if feature in Encodable_feilds_three_values:
           df[feature] = df[feature].apply(lambda x:0 if x == "No phone service" or x == "No internet service" else(1 if x=="No" else 2))
    return df
df = encoding_values(df)


# Convert some categorycal features into numeric so model can understand and drop old object fields

df['is_male'] = df["gender"].apply(lambda x:1 if x=='Male' else 0)
df = pd.get_dummies(df,columns=['PaymentMethod','InternetService'],drop_first=True,dtype=int)
df['Contract'] = df["Contract"].apply(lambda x:0 if x == 'Month-to-month' else(1 if x == 'One year'else 2 ))
df = df.drop(columns=['TotalCharges','gender'])

In [115]:
df.head()

   SeniorCitizen  Partner  ...  InternetService_Fiber optic  InternetService_No
0              0        1  ...                            0                   0
1              0        0  ...                            0                   0
2              0        0  ...                            0                   0
3              0        0  ...                            0                   0
4              0        0  ...                            1                   0

[5 rows x 22 columns]

In [116]:
# split data then scaled and performe SMOTE on train data
X = df.drop(columns=("Churn"))
y = df["Churn"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Smote = SMOTE(random_state=42)
X_train_res,y_train_res = Smote.fit_resample(X_train_scaled,y_train)

In [117]:
class MyCustomDataset(Dataset):

  def __init__(self,feature,label):
    self.feature = torch.tensor(feature,dtype=torch.float32)
    self.label  = torch.tensor(label,dtype=torch.long)

  def __len__(self):
    return len(self.feature)

  def __getitem__(self,index):
    return self.feature[index],self.label[index]

In [118]:
train_dataset  = MyCustomDataset(X_train_res,y_train_res.values)
test_dataset = MyCustomDataset(X_test_scaled,y_test.values)

In [119]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=False)

In [134]:
class MyNN(nn.Module):

  def __init__(self,feature_size):
    super().__init__()
    self.layers = nn.Sequential(
        nn.Linear(feature_size,32),
        nn.BatchNorm1d(32),
        nn.ReLU(),
        nn.Dropout(0.1),
        nn.Linear(32,16),
        nn.BatchNorm1d(16),
        nn.ReLU(),
        nn.Dropout(0.1),
        nn.Linear(16,1)
      )

  def forward(self,x):
    x = self.layers(x)
    return x

In [135]:
lr = 0.001
epochs = 100

In [136]:
model  = MyNN(X_train_res.shape[1])

optimizer = optim.Adam(model.parameters(),lr=lr,weight_decay=1e-4)

crierion = nn.BCEWithLogitsLoss()

In [137]:
for i in range(epochs):
  total_epoch_loss = 0
  for batch_featrue,batch_label in train_loader:

    output = model(batch_featrue)

    loss = crierion(output,batch_label.unsqueeze(1).float())

    optimizer.zero_grad()
    loss.backward()

    optimizer.step()

    total_epoch_loss +=loss.item()
  avg_loss = total_epoch_loss / len(train_loader)
  print(f'Epoch: {i + 1} , Loss: {avg_loss}')

Epoch: 1 , Loss: 0.5553031833015354
Epoch: 2 , Loss: 0.4840419787237543
Epoch: 3 , Loss: 0.48146580441578013
Epoch: 4 , Loss: 0.4738431246124179
Epoch: 5 , Loss: 0.46880890032039185
Epoch: 6 , Loss: 0.46777615273321
Epoch: 7 , Loss: 0.4674258067571058
Epoch: 8 , Loss: 0.46204335786200856
Epoch: 9 , Loss: 0.46302422593459197
Epoch: 10 , Loss: 0.45460659639485557
Epoch: 11 , Loss: 0.45356773973431824
Epoch: 12 , Loss: 0.45855248676303734
Epoch: 13 , Loss: 0.4525044565610444
Epoch: 14 , Loss: 0.45680763218623793
Epoch: 15 , Loss: 0.44758021474805115
Epoch: 16 , Loss: 0.44737888084415306
Epoch: 17 , Loss: 0.4520296510812399
Epoch: 18 , Loss: 0.4498388839734567
Epoch: 19 , Loss: 0.4434967154931838
Epoch: 20 , Loss: 0.44687575239932675
Epoch: 21 , Loss: 0.4456325781506461
Epoch: 22 , Loss: 0.4455214107128644
Epoch: 23 , Loss: 0.43789883930250484
Epoch: 24 , Loss: 0.4414068232056717
Epoch: 25 , Loss: 0.4437330817393815
Epoch: 26 , Loss: 0.4399695821595468
Epoch: 27 , Loss: 0.43209257894501263
Epoch: 28 , Loss: 0.44014226337427337
Epoch: 29 , Loss: 0.43171093742359556
Epoch: 30 , Loss: 0.44036960785913654
Epoch: 31 , Loss: 0.4347782019367549
Epoch: 32 , Loss: 0.4351373352829554
Epoch: 33 , Loss: 0.44276248315586547
Epoch: 34 , Loss: 0.43003487189994355
Epoch: 35 , Loss: 0.4308408814047294
Epoch: 36 , Loss: 0.4279222898616754
Epoch: 37 , Loss: 0.4347516287362714
Epoch: 38 , Loss: 0.42949039762314684
Epoch: 39 , Loss: 0.43464372804726414
Epoch: 40 , Loss: 0.43052598137883147
Epoch: 41 , Loss: 0.43351897677859746
Epoch: 42 , Loss: 0.4361577928641588
Epoch: 43 , Loss: 0.42714340490033725
Epoch: 44 , Loss: 0.43024464549935465
Epoch: 45 , Loss: 0.4273626719202314
Epoch: 46 , Loss: 0.42018218580129985
Epoch: 47 , Loss: 0.42377894023670654
Epoch: 48 , Loss: 0.4217459591084005
Epoch: 49 , Loss: 0.4243287503949464
Epoch: 50 , Loss: 0.4210470532243316
Epoch: 51 , Loss: 0.4186993846561918
Epoch: 52 , Loss: 0.42566140571386196
Epoch: 53 , Loss: 0.41735518375648956
Epoch: 54 , Loss: 0.4238545811774648
Epoch: 55 , Loss: 0.42368682712661715
Epoch: 56 , Loss: 0.42401613151244677
Epoch: 57 , Loss: 0.4155931351958094
Epoch: 58 , Loss: 0.4198499268431461
Epoch: 59 , Loss: 0.42290331032055223
Epoch: 60 , Loss: 0.4157778220862495
Epoch: 61 , Loss: 0.41866845134142283
Epoch: 62 , Loss: 0.4231276593268148
Epoch: 63 , Loss: 0.41781275302286774
Epoch: 64 , Loss: 0.4179592557165153
Epoch: 65 , Loss: 0.4159554619931806
Epoch: 66 , Loss: 0.42070116315569195
Epoch: 67 , Loss: 0.4274685618730125
Epoch: 68 , Loss: 0.4173238939069873
Epoch: 69 , Loss: 0.4161250164955279
Epoch: 70 , Loss: 0.41486748460406964
Epoch: 71 , Loss: 0.41466603914282957
Epoch: 72 , Loss: 0.41493690318812737
Epoch: 73 , Loss: 0.422787996102484
Epoch: 74 , Loss: 0.4145150343998979
Epoch: 75 , Loss: 0.4153811936212783
Epoch: 76 , Loss: 0.41400849859456756
Epoch: 77 , Loss: 0.4127899385902412
Epoch: 78 , Loss: 0.4083473878592598
Epoch: 79 , Loss: 0.4111020112244779
Epoch: 80 , Loss: 0.41832321755674357
Epoch: 81 , Loss: 0.4124577226671013
Epoch: 82 , Loss: 0.41445771619159744
Epoch: 83 , Loss: 0.4122202342311388
Epoch: 84 , Loss: 0.4141554602900067
Epoch: 85 , Loss: 0.4097910381882347
Epoch: 86 , Loss: 0.41292157467152624
Epoch: 87 , Loss: 0.41713930885073763
Epoch: 88 , Loss: 0.41989135788214255
Epoch: 89 , Loss: 0.4127430916407854
Epoch: 90 , Loss: 0.41973026775715433
Epoch: 91 , Loss: 0.40840597588813443
Epoch: 92 , Loss: 0.41378667340775716
Epoch: 93 , Loss: 0.41125709445550174
Epoch: 94 , Loss: 0.4058229766757332
Epoch: 95 , Loss: 0.408164244706106
Epoch: 96 , Loss: 0.41716818695593066
Epoch: 97 , Loss: 0.4105952985038168
Epoch: 98 , Loss: 0.40835882826891645
Epoch: 99 , Loss: 0.41551670679484554
Epoch: 100 , Loss: 0.4096326395351454

In [138]:
model.eval()

MyNN(
  (layers): Sequential(
    (0): Linear(in_features=21, out_features=32, bias=True)
    (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.1, inplace=False)
    (4): Linear(in_features=32, out_features=16, bias=True)
    (5): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.1, inplace=False)
    (8): Linear(in_features=16, out_features=1, bias=True)
  )
)

In [139]:
total = 0
correct = 0

with torch.no_grad():
  for batch_featrue,batch_label in test_loader:
    output = model(batch_featrue)
    predicted  = torch.round(torch.sigmoid(output))
    total += batch_label.size(0)
    correct += (predicted == batch_label.unsqueeze(1).float()).sum().item()
  print(correct/total)

0.7135749822316987

In [140]:
total = 0
correct = 0

with torch.no_grad():
  for batch_featrue,batch_label in train_loader:
    output = model(batch_featrue)
    predicted  = torch.round(torch.sigmoid(output))
    total += batch_label.size(0)
    correct += (predicted == batch_label.unsqueeze(1).float()).sum().item()
  print(correct/total)

0.8322033898305085