<a href="https://colab.research.google.com/github/Shivam-vachhani/PyTorch-Projects/blob/main/Neural_Network_form_nn_modules_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df = df.drop(columns=['id','Unnamed: 32'])
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df.shape

(569, 31)

# Train Test Split

In [ ]:
X =df.drop(columns=['diagnosis'])
y = df['diagnosis']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

# Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.42272563,  0.01082405,  0.32841425, ..., -0.47225261,
        -0.35384841, -0.87095838],
       [-0.80732035,  0.38335776, -0.79508238, ..., -0.84767361,
        -0.22845944,  0.23340914],
       [ 0.34289091, -1.18878137,  0.43565906, ...,  1.89039277,
         2.79516068,  0.83147167],
       ...,
       [ 1.66459897,  0.65982932,  1.61535196, ...,  1.88270287,
        -0.21893622, -0.44166418],
       [ 0.07086151,  0.10220024,  0.09161771, ...,  0.61694506,
        -0.29829633,  0.50758941],
       [-0.2307363 ,  0.27792369, -0.15890617, ...,  1.3644035 ,
         1.07780794,  1.45629682]])

#Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Numpy Arrays to Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_test_tensor.shape

torch.Size([114])

In [ ]:
X_train.shape

(455, 30)

In [ ]:
# create dataset and dataloader classes
from torch.utils.data import Dataset, DataLoader
class CustomDataSet(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [ ]:
# create dataLoader class
train_dataset = CustomDataSet(X_train_tensor,y_train_tensor)
test_dataset = CustomDataSet(X_test_tensor,y_test_tensor)

train_dataloader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_dataloader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Making Nural Network

In [ ]:
class NuralNetwork(nn.Module):

  def __init__(self,X_size):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(X_size,4),
        nn.ReLU(),

        nn.Linear(4,4),
        nn.ReLU(),

        nn.Linear(4,4),
        nn.ReLU(),

        nn.Linear(4,1),
        nn.Sigmoid(),
    )

  def forward(self, X):
    out = self.network(X)
    return out

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
#define model
model = NuralNetwork(X_train_tensor.shape[1])

#create optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=0.08)

#runs loop for epochs
epochs = 50
for epoch in range(epochs):
  for X_train_tensor,y_train_tensor in train_dataloader:
    #train data X
    y_pred = model(X_train_tensor.float())

    #getting loss
    loss = loss_function(y_pred,y_train_tensor.view(-1,1).float())

    # set all gradians to zero
    optimizer.zero_grad()

    # calculate deraviatives
    loss.backward()

    # update with new parameters values
    optimizer.step()


  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7712397575378418
Epoch: 2, Loss: 0.7479091882705688
Epoch: 3, Loss: 0.6602472066879272
Epoch: 4, Loss: 0.6650463938713074
Epoch: 5, Loss: 0.6384796500205994
Epoch: 6, Loss: 0.6750940084457397
Epoch: 7, Loss: 0.5196949243545532
Epoch: 8, Loss: 0.4890066087245941
Epoch: 9, Loss: 0.39281532168388367
Epoch: 10, Loss: 0.1855863332748413
Epoch: 11, Loss: 0.4082983136177063
Epoch: 12, Loss: 0.10617009550333023
Epoch: 13, Loss: 0.1520855873823166
Epoch: 14, Loss: 0.027989625930786133
Epoch: 15, Loss: 0.013588977046310902
Epoch: 16, Loss: 0.02834281511604786
Epoch: 17, Loss: 0.18004164099693298
Epoch: 18, Loss: 0.015272898599505424
Epoch: 19, Loss: 0.14517179131507874
Epoch: 20, Loss: 0.016208769753575325
Epoch: 21, Loss: 0.1222032830119133
Epoch: 22, Loss: 0.014743189327418804
Epoch: 23, Loss: 0.5322751998901367
Epoch: 24, Loss: 0.0226929672062397
Epoch: 25, Loss: 0.013764803297817707
Epoch: 26, Loss: 0.04290321469306946
Epoch: 27, Loss: 0.005740211345255375
Epoch: 28, Loss: 0.011131786741316319
Epoch: 29, Loss: 0.010439032688736916
Epoch: 30, Loss: 0.010403753258287907
Epoch: 31, Loss: 0.4126049876213074
Epoch: 32, Loss: 0.010477556847035885
Epoch: 33, Loss: 0.10062737762928009
Epoch: 34, Loss: 0.07397902756929398
Epoch: 35, Loss: 0.49009162187576294
Epoch: 36, Loss: 0.011588016524910927
Epoch: 37, Loss: 0.02636566571891308
Epoch: 38, Loss: 0.5037068724632263
Epoch: 39, Loss: 0.013357533141970634
Epoch: 40, Loss: 0.014732121489942074
Epoch: 41, Loss: 0.05884942784905434
Epoch: 42, Loss: 0.0021870445925742388
Epoch: 43, Loss: 0.0740337148308754
Epoch: 44, Loss: 0.00991260726004839
Epoch: 45, Loss: 0.041498929262161255
Epoch: 46, Loss: 0.037548065185546875
Epoch: 47, Loss: 0.0016458722529932857
Epoch: 48, Loss: 0.003474252298474312
Epoch: 49, Loss: 0.3840002715587616
Epoch: 50, Loss: 0.0011359445052221417

In [ ]:
model.eval()
accuracy_list=[]
with torch.no_grad():
  for X_test_tensor,y_test_tensor in test_dataloader:
    y_pred = model.forward(X_test_tensor.float())
    y_pred = (y_pred > 0.5).float()
    batch_accuracy = (y_pred.view(-1) == y_test_tensor).float().mean().item()
    accuracy_list.append(batch_accuracy)

  overall_acuracy = sum(accuracy_list)/len(accuracy_list)
  print(f'Accuracy: {overall_acuracy:.4f}')

Accuracy: 0.9861

# New Module class from scrach

In [ ]:
class Model(nn.Module):

  def __init__(self,num_featurs):
    super().__init__()
    self.linear = nn.Linear(num_featurs,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,featurs):
    out = self.linear(featurs)
    out = self.sigmoid(out)

    return out

In [ ]:
#create features
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model forward pass
#model.forward(features) we can dierectly call forward by only calling the  object
model(features)

tensor([[0.6326],
        [0.6606],
        [0.5854],
        [0.6249],
        [0.6238],
        [0.6365],
        [0.5735],
        [0.6655],
        [0.5544],
        [0.5794]], grad_fn=<SigmoidBackward0>)

In [ ]:

model.linear.weight

Parameter containing:
tensor([[ 0.4228, -0.1326,  0.0545,  0.4085, -0.0390]], requires_grad=True)

In [ ]:
! pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [ ]:
from torchinfo import summary

In [ ]:
summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================