<a href="https://colab.research.google.com/github/Shivam-vachhani/PyTorch-Projects/blob/main/Nural_Network_From_Scrach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df = df.drop(columns=['id','Unnamed: 32'])
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
df.shape

(569, 31)

# Train Test Split

In [ ]:
X =df.drop(columns=['diagnosis'])
y = df['diagnosis']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

# Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.92488008, -1.60366819, -0.95149109, ..., -1.2580974 ,
        -1.22524798, -0.92157846],
       [-1.21718441,  0.01751193, -1.16463232, ..., -0.25771489,
        -0.44304155,  0.06591684],
       [ 0.20871798, -1.01038525,  0.17006711, ...,  0.00493321,
        -0.33526363, -0.05010183],
       ...,
       [ 2.28650994,  0.07959968,  2.48423059, ...,  2.69551195,
         1.89704574,  0.7604249 ],
       [ 0.01931382,  0.55100666,  0.05425627, ...,  0.46277418,
         1.13933429,  0.94808644],
       [ 0.58187246, -0.12735949,  0.67725289, ...,  0.89772309,
        -0.20135773,  1.21006407]])

#Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Numpy Arrays to Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_test_tensor.shape

torch.Size([114])

In [ ]:
X_train.shape

(455, 30)

# Making Nural Network

In [ ]:
class NuralNetwork():

  def __init__(self,X,layer_size=[4,4,4,1]):

    input_features = X.shape[1]
    self.layer_sizes = [input_features] + layer_size

    self.weights = []
    self.bias = []

    for i in range(len(self.layer_sizes) - 1):
      self.weights.append(torch.rand(self.layer_sizes[i+1], self.layer_sizes[i], dtype=torch.float64, requires_grad=True))
      self.bias.append(torch.zeros(self.layer_sizes[i+1], dtype=torch.float64, requires_grad=True))

  def forward(self, X):
    current_input = X

    for i in range(len(self.weights)):
      output_values = torch.matmul(current_input,self.weights[i].T)+ self.bias[i]
      current_input = torch.sigmoid(output_values)
    return current_input


  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y * torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
    print(loss)
    return loss

In [ ]:

model = NuralNetwork(X_train_tensor)
epochs = 50
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  loss = model.loss_function(y_pred,y_train_tensor)
  loss.backward()
  with torch.no_grad():
    for i in range(len(model.weights)):
      model.weights[i] -= 0.1 * model.weights[i].grad
      model.bias[i] -= 0.1 * model.bias[i].grad

      model.weights[i].grad.zero_()
      model.bias[i].grad.zero_()

print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

tensor(1.1070, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(1.0404, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.9819, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.9312, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.8877, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.8506, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.8192, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7929, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7709, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7526, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7374, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7248, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7144, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.7059, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6988, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6930, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6882, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6842, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6809, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6782, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6760, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6741, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6726, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6714, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6703, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6695, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6687, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6681, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6677, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6672, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6669, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6666, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6664, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6662, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6660, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6659, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6658, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6657, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6656, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6656, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6655, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6655, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6654, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6654, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6654, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6653, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6653, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6653, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6653, dtype=torch.float64, grad_fn=<NegBackward0>)
tensor(0.6653, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 50, Loss: 0.665290509743427

In [ ]:
model.bias

[tensor([-0.0009, -0.0003, -0.0004, -0.0006], dtype=torch.float64,
        requires_grad=True),
 tensor([-0.0073, -0.0111, -0.0052, -0.0121], dtype=torch.float64,
        requires_grad=True),
 tensor([-0.0065, -0.0187, -0.0492, -0.0030], dtype=torch.float64,
        requires_grad=True),
 tensor([-0.5162], dtype=torch.float64, requires_grad=True)]

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6666666865348816